"use client";
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import { SessionProvider } from "next-auth/react";
import { ReactNode } from "react";

export default function RootLayout({ children} ) {
  return (
    <html lang="en">
      <body>
        <SessionProvider >
          <div className={"  h-screen "}>{children}</div>
        </SessionProvider>
      </body>
    </html>
  );
}
